### ISSUE TITLE
string translations + coverage

### ISSUE THREAD

**Issue by Razish** [CleanJK/cleanjk#42]
## tasks

- [x] amalgamate language directories in `strings/` to a mega translation file -- done
- [ ] sweep string literals/hardcoded messages for stringed candidates. keep this in mind for future code.
- [ ] think about using a new file format (json ftw?)
- [ ] tool to check translation coverage (build/package step?)
  a tool exists (in the aether) to cross-check strings that have been translated to specific language.
  a special token is used to indicate "same as original language".
  we can write our own equivalent, easier with a new format.

## targeted languages

We only target a small amount of languages due to both human resource availability and code complexity.

- English (main)
- French (TL: @Yberion)
- ???

**Comment by TriForceX** [comment]
Spanish 👍

**Comment by ensiform** [comment]
What about switching to utf8 support?

**Comment by TriForceX** [comment]
Since encoding problems can be weird and difficult to deal with, utf-8 should be the default for any library/application nowadays because it allows you to display all characters for all languages

**Comment by Exmirai** [comment]
ready to translate to russian

**Comment by admafi** [comment]
I could translate to German if needed

**Comment by ensiform** [comment]
There's services for that if you use a more standard format

**Comment by TrayHard** [comment]
Ready to translate everything in Russian 👌
